# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install wget
RUN apt-get update && apt-get install -y wget

# Download and install cloudflared
RUN wget -O /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && \
    chmod +x /usr/local/bin/cloudflared

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World

# Copy run.sh and make it executable
#COPY run.sh /app/run.sh
#RUN chmod +x /app/run.sh

# Run both uvicorn and cloudflared when the container launches
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8080 && cloudflared tunnel --no-autoupdate run eyJhIjoiMWY1NmQxNjAyMjNiZjhmODMwNzIwNTM1ZDk5ZGFkODIiLCJ0IjoiMmZiNDllM2QtZDc5Zi00MjU3LTgwMGYtMTRkYTgwZGI1N2FlIiwicyI6Ik9EZzBOV0kxWlRndFpHTmtPUzAwWVRJM0xXRmlNbUV0TWpJMlkyRXdPRGN4WkRVMCJ9"]